// ============================================================
// RIFTS RPG - Cybernetics
// Adds cybernetic implants (Medical + Appendages, Prosthetics
// & Bone) to the "Rifts Armory" compendium, organized:
//   Cybernetics > Medical > (location)
//   Cybernetics > Appendages & Bone > (location)
// Safe to re-run: skips existing by name, moves items into
// the correct folders.
// ============================================================

const PACK_NAME = "rifts-armory";
const PACK_LABEL = "Rifts Armory";

let pack = game.packs.get(`world.${PACK_NAME}`);
if (!pack) {
  pack = await foundry.documents.collections.CompendiumCollection.createCompendium({
    label: PACK_LABEL,
    name: PACK_NAME,
    type: "Item",
  }).catch(async () => {
    return await CompendiumCollection.createCompendium({
      label: PACK_LABEL,
      name: PACK_NAME,
      type: "Item",
    });
  });
  ui.notifications.info(`Created compendium: ${PACK_LABEL}`);
}

// ── Nested folder helper ───────────────────────────────────
async function getOrCreateFolder(name, parent = null) {
  let f = pack.folders.find(
    (x) => x.name === name && (x.folder?.id ?? null) === (parent?.id ?? null)
  );
  if (!f) {
    f = await Folder.create(
      { name, type: "Item", folder: parent?.id ?? null },
      { pack: pack.collection }
    );
  }
  return f;
}

const cyberRoot = await getOrCreateFolder("Cybernetics");
const medical = await getOrCreateFolder("Medical", cyberRoot);
const appendages = await getOrCreateFolder("Appendages & Bone", cyberRoot);
const bioSystems = await getOrCreateFolder("Bio-Systems", cyberRoot);

const loc = {};
for (const n of ["Hand", "Finger"]) loc[`med:${n}`] = await getOrCreateFolder(n, medical);
for (const n of ["Finger & Toe", "Hand", "Arm", "Leg & Foot", "Torso & Skeleton", "Head"])
  loc[`app:${n}`] = await getOrCreateFolder(n, appendages);
for (const n of ["Eyes", "Head", "Internal Organs"]) loc[`bio:${n}`] = await getOrCreateFolder(n, bioSystems);
const lungImplants = await getOrCreateFolder("Lung Implants", cyberRoot);
loc["lung"] = lungImplants;
const commercial = await getOrCreateFolder("Commercial", cyberRoot);
for (const n of ["Eyes", "Sensors & Implants", "Audio & Ear", "Cosmetic", "Head Shaping & Body Mods"])
  loc[`com:${n}`] = await getOrCreateFolder(n, commercial);

// ── Item helper ────────────────────────────────────────────
const cyber = (name, folderKey, cost, description, notes) => ({
  name,
  type: "equipment",
  img: "icons/commodities/tech/metal-panel.webp",
  folder: loc[folderKey].id,
  system: { quantity: 1, weight: "", cost, description, notes },
});

// ── Item definitions ──────────────────────────────────────
const items = [

  // ═══ MEDICAL ═════════════════════════════════════════════
  cyber("Medical: Blood Analysis/Tox-Screen", "med:Hand", 30000,
    "Special sensors and implants in the hand enable a basic screen for 60 common toxins and blood anomalies (too much or too little insulin, sugar, cholesterol, white and red cell count, poison, etc.). The subject's blood must physically touch the area of the hand (a particular finger or area of the palm) to do the analysis. Can also indicate whether the sample is human, animal, D-Bee or unknown (alien) blood type.",
    "Location: Hand or Finger."),
  cyber("Medical: Epidermic Analyzer", "med:Hand", 35000,
    "Molecular analyzers in the hand identify and measure the amount of salt, sugar and powerful enzymes or chemicals by touching a person's skin and/or perspiration. Can also measure the patient's body temperature by touch (touch for 30 seconds).",
    "Location: Hand."),
  cyber("Medical: Epidermal Temperature Gauge", "med:Hand", 1000,
    "The hand or a specific finger can take a person's body temperature by simply touching the subject on the neck, head or armpits.",
    "Location: Hand or Finger."),
  cyber("Medical: Laser Scalpel Finger", "med:Finger", 5000,
    "One of the fingers is really a laser scalpel used for surgery. Maximum damage is 1D4 S.D.C. It is not a Mega-Damage weapon.",
    "Location: Finger. Improvised weapon: 1D4 S.D.C. max."),
  cyber("Medical: Pulse & Pressure Detector", "med:Hand", 25000,
    "By squeezing and holding a patient's wrist or finger for a minute, the doctor can accurately measure the character's pulse rate. By squeezing, holding and slowly releasing the wrist, the doctor can also measure the patient's blood pressure.",
    "Location: Hand."),
  cyber("Medical: Stethoscope Feature", "med:Hand", 10000,
    "Can only be used in conjunction with one of the cybernetic or bionic ear implants or a universal Head-jack and receiver. The doctor uses his hand or ear like a stethoscope, placing it on the patient's chest or back to listen to heartbeat and/or breathing.",
    "Location: Hand. Requires a cybernetic/bionic ear implant or Headjack."),
  cyber("Medical: Sensor Hand", "med:Hand", 60000,
    "Closely resembles an ordinary sensor hand, except designed with medical care rather than general utility in mind. As many as 14 features can be installed in the hand; each sensor feature must be purchased separately. Includes all Medical features plus 1D4 other cybernetic systems.",
    "Location: Hand. Up to 14 features; each purchased separately."),

  // ═══ APPENDAGES, PROSTHETICS & BONE ═════════════════════
  cyber("Cybernetic Finger (or Toe)", "app:Finger & Toe", 300,
    "A bio-mechanical replacement digit for a lost finger, usually sized and molded to resemble the remaining fingers as closely as possible.",
    "Location: Finger or Toe. P.S. 4-8, S.D.C. 1D4.\nCost tiers: 300 cr standard cybernetic; 1,000 cr cybernetic Bio-System; 2,000 cr full flesh-and-blood Bio-System (like real)."),
  cyber("Cybernetic Foot", "app:Leg & Foot", 10000,
    "A bio-mechanical replacement for a lost foot, fitted to be as similar in shape and size as possible to the lost appendage.",
    "Location: Foot. P.S. 8-10, supports Spd 10, S.D.C. 2D6+25.\nCost tiers: 10,000 cr standard mechanical; 16,000 cr cybernetic + Bio-System; 24,000 cr full flesh-and-blood Bio-System."),
  cyber("Cybernetic Hand", "app:Hand", 12000,
    "A bio-mechanical replacement for a lost hand, fitted to be as similar in shape and size as possible to the lost appendage.",
    "Location: Hand. P.S. 8-10, P.P. 8-10, S.D.C. 2D6+16.\nCost tiers: 12,000 cr standard mechanical; 18,000 cr cybernetic + Bio-System; 30,000 cr full flesh-and-blood Bio-System."),
  cyber("Cybernetic Hand & Forearm", "app:Arm", 12000,
    "A bio-mechanical replacement for a lost hand and forearm, fitted to be as similar in shape and size as possible to the lost appendage.",
    "Location: Hand & Forearm. P.S. 8-10, P.P. 10, S.D.C. 2D6+24. Weight ~6 lbs (2.7 kg).\nCost tiers: 12,000 cr standard mechanical; 22,000 cr cybernetic Bio-System; 40,000 cr full flesh-and-blood Bio-System."),
  cyber("Cybernetic Hand & Entire Arm", "app:Arm", 24000,
    "A cybernetic prosthetic of the entire arm from fingertip to shoulder.",
    "Location: Entire Arm. P.S. 8-10, P.P. 10, S.D.C. 3D6+30. Weight ~8-9 lbs (3.6-4 kg).\nCost tiers: 24,000 cr standard mechanical; 38,000 cr cybernetic + Bio-System; 75,000 cr full flesh-and-blood Bio-System."),
  cyber("Cybernetic Leg & Foot", "app:Leg & Foot", 25000,
    "A bio-mechanical replacement for a lost leg and foot.",
    "Location: Leg & Foot. P.S. 10-12, P.P. 10, supports Spd 12, S.D.C. 3D6+40. Weight ~15 lbs (6.7 kg).\nCost tiers: 25,000 cr standard mechanical; 40,000 cr cybernetic + Bio-System; 80,000 cr full flesh-and-blood Bio-System."),
  cyber("Rebuild Hip & Leg Joint", "app:Torso & Skeleton", 25000,
    "Rebuild of the hip area, compatible with the original or a cybernetic leg.",
    "Location: Hip/Pelvis. P.S. 10, P.P. 10, S.D.C. 2D6+30. Weight ~5 lbs (2.25 kg).\nCost tiers: 25,000 cr standard mechanical; 35,000 cr cybernetic + Bio-System; 70,000 cr full flesh-and-blood Bio-System. DOUBLE cost to completely replace the pelvis."),
  cyber("Rebuild Shoulder & Shoulder Blade", "app:Torso & Skeleton", 20000,
    "Rebuild of the shoulder area, compatible with the original or a cybernetic arm.",
    "Location: Shoulder. P.S. 8-10, P.P. 10, S.D.C. 2D6+30. Weight ~5 lbs (2.25 kg).\nCost tiers: 20,000 cr standard mechanical; 32,000 cr cybernetic + Bio-System; 50,000 cr full flesh-and-blood Bio-System."),
  cyber("Reinforced Bones", "app:Torso & Skeleton", 250000,
    "An S.D.C. or M.D.C. metal and ceramic bone replaces the original. May be done for medical reasons (bone cancer, shattered bone, etc.) or to provide reinforced bones for combat or hazardous labor. Original skin and muscle is put over the synthetic bone structure. Most of the cost is the long and dangerous surgery — a very painful procedure.",
    "Location: per appendage, rib cage or pelvis (does NOT include spine). S.D.C. 90, or 1D6+10 M.D.C. per appendage.\nCost: 250,000 cr S.D.C. / 450,000 cr M.D.C. per appendage/rib cage/pelvis.\nBonus: +2D6+20 to overall S.D.C. if more than 50% of the bones have been replaced."),
  cyber("Cybernetic Spine (Vertebrae)", "app:Torso & Skeleton", 25000,
    "Spinal surgery is tricky and dangerous even for the advanced medicine of Rifts Earth's most technological civilizations. Cybernetic replacement pieces can replace broken and crushed vertebrae to restore the spine to as good as new. Back pain is completely gone after healing.",
    "Location: Spine. Cost: 25,000 cr per vertebra; 750,000 cr to completely replace the spine with a cybernetic system (three times more durable than the original; 80 S.D.C.). An M.D.C. spine is considered bionic augmentation."),
  cyber("Skull Case", "app:Head", 60000,
    "50-100% of the cranium is replaced with a synthetic one, usually to replace a shattered skull, shaped to resemble the original head as closely as possible. May be done for medical reasons or to provide a reinforced skull for combat or hazardous labor personnel. Original skin is put over the skull casing.",
    "Location: Head/Skull. S.D.C. 100, or 1D6+16 M.D.C. Weight ~3-5 lbs (1.35-2.25 kg).\nCost: 60,000 cr S.D.C. / 120,000 cr M.D.C. casing (most of the cost is the long and dangerous brain surgery)."),

  // ═══ BIO-SYSTEM EYES ═════════════════════════════════════
  cyber("Infrared/Ultra-V Eye (Bio-System)", "bio:Eyes", 70000,
    "A natural but unusual looking eye — the pupil is noticeably larger than normal and the iris is an unusual violet or alizarin color. Enables sight into the infrared and ultraviolet spectrums: see in the dark equal to an infrared camera (range about half of normal day vision) and see IR/UV light invisible to humans. Color perception changes — sees blue, green and ultraviolet, so everything appears in purple-blues, deep greens, purple and violet, like wearing red or purple tinted sunglasses all the time. 20/20 vision.",
    "Location: Eye. CANNOT see the invisible nor heat emanations — only red (infrared) and ultraviolet light.\nCost: 70,000 cr single / 125,000 pair. Half cost for a cybernetic version."),
  cyber("\"Lifelike\" Simulated Eye (Bio-System)", "bio:Eyes", 20000,
    "A natural, realistic eye that appears and functions exactly like the real thing, created in the laboratory with synthetic tissue and nano-technology. Choice of eye color. Perfect 20/20 vision.",
    "Location: Eye. Cost: 20,000 cr per eye / 35,000 pair if installed at the same time. Half cost for a cybernetic version."),
  cyber("Mood or Color-Changing Eyes (Bio-System)", "bio:Eyes", 24000,
    "No special powers other than the eyes look natural and real, but can change 2-8 different colors to reflect the wearer's moods. 20/20 vision.",
    "Location: Eyes (pair). Cost: 24,000 cr for a pair of 20/20 Bio-System eyes, plus 800 cr per each color it can change to. Half for a lifelike pair of cybernetic eyes."),
  cyber("Nightvision Eyes (Bio-System)", "bio:Eyes", 32000,
    "Perfect 20/20 daytime vision, plus a chip placed in or on the cornea gives the recipient keen nightvision. Not quite as good as mechanical passive nightvision, but close: see clearly at night up to 800 feet (244 m) — roughly equal to normal vision in a dimly lit room. Very popular among guards, police, detectives, thieves, spies, and people who work (or play) at night.",
    "Location: Eye. Nightvision 800 ft (244 m). Cost: 32,000 cr per eye / 58,000 pair if installed simultaneously."),
  cyber("Polarized Eye (Bio-System)", "bio:Eyes", 30000,
    "Looks completely natural, but has light-adjusting polarized filters to reduce glare. Bright light and sunlight are filtered as if wearing the best polarized sunglasses available; can look directly into the sun without being blinded. Engages automatically as needed. Choice of eye color. Perfect 20/20 vision.",
    "Location: Eye. Cost: 30,000 cr per eye / 53,000 pair if installed at the same time. Half cost for a cybernetic version."),
  cyber("Underwater Eye (Bio-System)", "bio:Eyes", 35000,
    "The cornea automatically distorts when submerged, compensating for the watery environment without goggles. Crystal-clear underwater vision in low light to depths of 600 feet (183 m). Contains a self-replicating oil released when water is murky or bright — haze filters that reduce glare and filter reflections and debris haze. The oil also releases above water in bright light, creating an instant filter/sunglasses effect (equal to a cheap pair of sunglasses). 20/20 vision. Choice of eye color.",
    "Location: Eye. Underwater vision to 600 ft (183 m) depth. Cost: 35,000 cr single / 65,000 pair if purchased together. Half for a mechanical cybernetic version."),

  // ═══ BIO-SYSTEMS FOR THE HEAD ════════════════════════════
  cyber("Inner Ear (Bio-System)", "bio:Head", 20000,
    "Completely rebuilds the inner ear and eardrum to create perfect human hearing. No augmentation.",
    "Location: Ear. Cost: 20,000 cr per ear / 36,000 for the pair if done at the same time."),
  cyber("Outer Ear (Bio-System)", "bio:Head", 2000,
    "A cosmetic procedure that replaces a damaged or missing outer ear with a natural living ear. Looks and feels just like the genuine article; no scarring.",
    "Location: Ear (outer). Cost: 1,500-2,000 cr for a replacement matching the original ear's skin color perfectly; 500 cr for a generic replacement that matches neither skin color nor shape."),
  cyber("Nasal Passages (Bio-System)", "bio:Head", 5000,
    "Restores or replaces damaged nasal passages with synthetic skin and olfactory sensors. Duplicates the natural human ability to smell at 75%.",
    "Location: Nose (internal). Smell at 75%. Cost: 5,000 cr."),
  cyber("Outer Nose (Bio-System)", "bio:Head", 2000,
    "A cosmetic procedure that replaces a damaged or missing nose with natural looking living tissue built over a synthetic frame.",
    "Location: Nose (outer). Cost: 2,000 cr to match the original nose (or a nose structure of choice) and skin color perfectly; 900 cr for a generic replacement that may be a little too big, small, or wide."),
  cyber("Lips (Bio-System)", "bio:Head", 600,
    "A cosmetic procedure that replaces damaged or missing lips with natural looking and feeling living tissue; good as new. Now give me a kiss.",
    "Location: Mouth. Cost: 600 cr."),
  cyber("Tongue (Bio-System)", "bio:Head", 14000,
    "Replaces a damaged tongue with a synthetic one composed of living tissue, blood vessels, and taste buds/sensors. Duplicates the natural ability to taste at 63% and offers full speech articulation.",
    "Location: Mouth. Taste at 63%; full speech. Cost: 14,000 cr."),
  cyber("Larynx and Voice Box (Bio-System)", "bio:Head", 18000,
    "Replaces the damaged organ with a synthetic but lifelike Bio-System that simulates human sound/voice. The voice can simulate the original exactly, as long as a quality recording is provided — or the patient may create a new voice by selecting the desired aspects and qualities, all programmed into the replacement unit.",
    "Location: Throat. Cost: 18,000 cr."),

  // ═══ BIO-SYSTEM INTERNAL ORGANS ══════════════════════════
  cyber("Artificial Heart (Bio-System)", "bio:Internal Organs", 70000,
    "Bio-System replacement heart.", "Location: Chest. 40 year life. Cost: 70,000 cr."),
  cyber("Artificial Lungs (Bio-System)", "bio:Internal Organs", 50000,
    "Bio-System replacement lungs.", "Location: Chest. 40 year life. Cost: 50,000 cr."),
  cyber("Artificial Kidney (Bio-System)", "bio:Internal Organs", 30000,
    "Bio-System replacement kidney.", "Location: Torso. 30 year life. Cost: 30,000 cr."),
  cyber("Artificial Liver (Bio-System)", "bio:Internal Organs", 30000,
    "Bio-System replacement liver.", "Location: Torso. 30 year life. Cost: 30,000 cr."),
  cyber("Artificial Spleen (Bio-System)", "bio:Internal Organs", 30000,
    "Bio-System replacement spleen.", "Location: Torso. 30 year life. Cost: 30,000 cr."),
  cyber("Artificial Intestine (Bio-System)", "bio:Internal Organs", 10000,
    "Bio-System replacement intestine.", "Location: Torso. 25 year life. Cost: 10,000 cr."),
  cyber("Artificial Skin / Plastic Surgery (Bio-System)", "bio:Internal Organs", 0,
    "Synthetic skin grafts and reconstructive surgery. 50 year life.",
    "Location: varies. Cost varies by complexity: 1D4x1,000 cr for minor skin grafts (hand or small fleshy area); 2D6x1,000 for minimal work on a large fleshy area (leg or back); 1D4x10,000+ for muscle and skin reconstruction; 2D6x10,000+ for muscle, skin and bone reconstruction. Add 20% when working on the face."),

  // ═══ CYBERNETIC LUNG IMPLANTS ════════════════════════════
  cyber("Molecular Analyzer (Lung Implant)", "lung", 35000,
    "Micro-chip based sensor for testing and analyzing impurities in the air. Specifically identifies any chemical or strange/dangerous molecules — gas, oil, pollution, or other chemicals. Data can be transmitted as an audio report through an ear implant or to a wristwatch-like receiver.",
    "Location: Lungs/Chest. Does NOT enable tracking. Cost: 35,000 cr. (Cybernetic version — the bionic model in Cyborg > Bionics costs 50,000.)"),
  cyber("Oxygen Storage Cell (Lung Implant)", "lung", 60000,
    "A special chemical cell, controlled by micro-processors, that stores oxygen from the character's normal breathing. When oxygen is low, it is released back into the lungs — the character can go without breathing for up to 30 minutes.",
    "Location: Lungs/Chest. 30 minutes without breathing; must breathe normally for about an hour to recharge between uses. Cost: 60,000 cr."),
  cyber("Toxic Filter (Lung Implant)", "lung", 40000,
    "A mechanism designed to filter most toxic gases out before they enter the lungs. Effective against all types of tear gas, smoke, and purely chemical fumes.",
    "Location: Lungs/Chest. 80% chance to also work against nerve gases and poison gases. Cost: 40,000 cr."),

  // ═══ COMMERCIAL CYBERNETICS — EYES ═══════════════════════
  cyber("Cyber-Camera Eye (Cybernetic)", "com:Eyes", 30000,
    "Looks like an ordinary cybernetic eye and provides 20/20 sight, but is also a digital (or video) camera that records and/or transmits everything seen. Live feed is most common; up to one hour of filming can be recorded on a memory chip.",
    "Location: Eye. Transmission range 20 mi (32 km) city / 60 mi (96 km) wilderness. Cost: 30,000 cr single basic color+sound / 50,000 pair. +20,000 synchronized digital audio recording/transmission; +40,000 broadband (doubles transmission range). Sometimes illegal for average citizens. Illegal in the CS."),
  cyber("Cyber-Camera Studio Eye", "com:Eyes", 20000,
    "A concealed cybernetic recording device — typically one eye or a third eye — providing NO simulated vision, but a fully miniaturized video camera system. Records everything the person sees and hears onto a two- or four-hour video disc in a skull implant; the disc ejects from a tiny slot for replacement. A Headjack enables plugging directly into a monitor to display/record without removing the disc, and into duplicating equipment to dupe recordings onto other media or transmit them.",
    "Location: Eye (replaces vision in that eye). Cost: 20,000 cr. Sometimes illegal for average citizens. Illegal in the CS."),
  cyber("Cyber-Lens Implant", "com:Eyes", 500,
    "A simple implant inserted into the eye to correct common problems: nearsightedness, farsightedness, astigmatism, degenerative myopia. Has replaced eyeglasses wherever available. Instantly restores vision to 20/20.",
    "Location: Eye. Cost: 400-600 cr per eye."),
  cyber("\"Lifelike\" Simulated Eye (Cybernetic)", "com:Eyes", 12000,
    "A natural, realistic cyber-eye that appears and functions exactly like the real thing, created with lens, plastic and nano-technology. Choice of eye color. Perfect 20/20 vision.",
    "Location: Eye. Cost: 12,000 cr per eye / 20,000 pair if installed at the same time."),
  cyber("Infrared Eye (Cybernetic)", "com:Eyes", 6000,
    "Relies on a pencil-thin beam of infrared light projected from the eye to the target; the narrow beam limits viewing to about a 7 ft (2.1 m) area. Also simulates normal human vision.",
    "Location: Eye. Range 1,200 ft (366 m). Cost: 6,000 cr / 9,000 pair."),
  cyber("Macro-Eye (Cybernetic)", "com:Eyes", 20000,
    "A robot-looking eye that magnifies tiny objects at close range (within 3 ft / 0.9 m) — magnifying glass to microscope magnification (2x to 50x). Equipped with filters to block glare and dust. Extremely popular among medics, doctors, forgers and engineers (great for spotting defects and cracks).",
    "Location: Eye. Cost: 20,000 cr per eye; photographic camera (still or video) +10,000. See also Modular Eye Socket. A character would seldom get two Macro-Eyes."),
  cyber("Macro-Eye Laser", "com:Eyes", 80000,
    "Very similar to the standard Macro-Eye but with a tiny surgical laser built in. A targeting beam indicates exactly where the laser will fire before it is engaged. Used exclusively for internal surgery — inflicts little discernible damage to external targets (one S.D.C. point). A favorite of doctors and surgeons.",
    "Location: Eye. Magnification limited to 2x-30x. Cost: 80,000 cr. A character would seldom get two Macro-Eyes."),
  cyber("Mechanical Eye w/ Polarized Filter", "com:Eyes", 10000,
    "A robot-looking eye simulating normal human vision, with polarized vision added. Bright light and sunlight are polarized as if wearing the best sunglasses available; can look directly into the sun without being blinded. Engages automatically. Choice of lens color. Perfect 20/20 vision.",
    "Location: Eye. Cost: 10,000 cr per eye / 16,000 pair installed at the same time. (Standard issue for starting Combat Cyborgs.)"),
  cyber("Modular Eye Socket (Multi-System)", "com:Eyes", 100000,
    "The eye socket is designed to allow the wearer to remove the artificial eye and replace it with any eye made to fit the universal modular housing. Modular eyes can be swapped as needed or desired.",
    "Location: Eye socket. Cost: 100,000 cr for the socket housing (half what it cost ten years ago), plus 10,000 cr per eye to fit it with modular capability (pops in and out with ease). Bio-System eyes do NOT work in this housing — mechanical types only."),
  cyber("Multi-Optic Eye (Cybernetic)", "com:Eyes", 60000,
    "A mechanical optic system with multiple systems in a single cyber-eye: Telescopic (4-8x30, 6,000 ft / 1,829 m), Macro Lens (2x-8x, 3 ft), Passive Night-vision (2,000 ft), Thermo-Imaging (2,000 ft), Light Filters (reduces glare), Targeting Display (cross-hairs, +1 to strike with any ranged weapon — same bonus for one or two eyes).",
    "Location: Eye. Cost: 55,000-60,000 cr per eye / 100,000 pair installed together. (Cybernetic macro lens is 2x-8x vs the bionic model's 2x-20x.)"),
  cyber("Night-Eyes (Cybernetic)", "com:Eyes", 32000,
    "Perfect 20/20 daytime vision, plus a chip in the cornea or on the retinal cord gives passive night-vision — roughly equal to normal vision in a dimly lit room. Very popular among guards, police, detectives, thieves, spies, City Rats, and people who work (or play) at night.",
    "Location: Eye. See clearly at night up to 400 ft (122 m). Cost: 32,000 cr per eye / 58,000 pair installed simultaneously. (Bio-System Nightvision Eyes reach 800 ft.)"),
  cyber("Optic Nerve Video Implant (Cybernetic)", "com:Eyes", 35000,
    "Implants an optical sensor right on the optic nerve. Works like the Headjack's inner-ear implant, but for video: the recipient sees video transmissions in his head/eyes. Incredibly useful for secretly monitoring video transmissions and discs. Combined with a Headjack, enables both seeing and hearing audio-visual messages.",
    "Location: Optic nerve. Cost: 35,000 cr (delicate operation). Blind restoration experiments: 1-45% full restoration, 46-80% restores 65%, 81-95% restores 40%, 96-00% restores 10% (legally blind). Sometimes illegal for average citizens. Illegal in the CS."),
  cyber("Telescopic Eye (Cybernetic)", "com:Eyes", 12000,
    "In addition to normal 20/20 vision, the eye has a telescopic lens for long-distance viewing (4-10x50 magnification).",
    "Location: Eye. Range 6,000 ft (1,829 m). Cost: 12,000 cr / 20,000 pair."),
  cyber("Targeting Sight (Eye Feature)", "com:Eyes", 4000,
    "A feature addable to any of the mechanical eyes. Cross-hairs are superimposed over the visual image to help focus on a specific target area.",
    "Location: Eye (feature). +1 to strike with any weapon; two targeting eyes still provide only +1, not +2. Cost: 4,000 cr. Sometimes illegal for average citizens. Illegal in the CS."),
  cyber("Thermo-Imager Eye (Cybernetic)", "com:Eyes", 12000,
    "Simulates normal human vision with an optical heat sensor added. The lens converts infrared radiation of warm objects into a visible image — see heat as bands of color, in darkness, shadows, and through smoke. Perfect 20/20 vision.",
    "Location: Eye. Range 3,000 ft (914 m). Cost: 12,000 cr / 20,000 pair. Sometimes illegal for average citizens. Illegal in the CS."),
  cyber("Third Eye", "com:Eyes", 350000,
    "A cybernetic eye implanted either above a real eye or in the center of the forehead. The mechanical eye can be any of the available artificial eyes, but is typically one of the camera eyes or a Multi-Optic eye.",
    "Location: Forehead. Cost: 350,000 cr. PENALTY: reduce the character's P.B. by 20%. Sometimes illegal for average citizens. Illegal in the CS."),

  // ═══ COMMERCIAL SENSORS & IMPLANTS ═══════════════════════
  cyber("Air & Surface Temperature Reader", "com:Sensors & Implants", 5000,
    "Typically built into the hand or wrist (or neck/head). Precisely measures hot and cold temperatures from objects or areas — tell if an engine was recently used, how old a campfire is, whether a weapon was recently fired, or measure the surrounding air temperature. For extremely hot items, take the reading by placing the sensor NEAR the source; touching something extremely hot burns even a cybernetic hand.",
    "Location: Hand/Wrist (or Neck/Head). Range: touch or 4-6 inches. Cost: 5,000 cr. Not suited for taking a living creature's temperature — see Medical: Epidermal Temperature Gauge."),
  cyber("Bio-Comp Self-Monitoring System", "com:Sensors & Implants", 2500,
    "A nano-implant tied to a tiny computer that monitors, measures and transmits fundamental physiological data: pulse rate, blood pressure, body temperature, blood sugar, respiratory rate/difficulty, and foreign elements in the bloodstream indicating drugs or poison. Displays on a wristwatch/bracelet monitor, cybernetic or bionic eyes, or a computer/bio-scan device via Finger- or Headjack.",
    "Location: internal. Cost: 2,500 cr."),
  cyber("Clock Calendar (Cybernetic)", "com:Sensors & Implants", 200,
    "Implanted almost anywhere. Continuously tracks exact time to 1/100th of a second plus calendar date. Data transmitted as audio through an ear implant, or to a wristwatch-like receiver, cybernetic eye and/or computer screen (latter requires Finger- or Headjack).",
    "Location: anywhere. Cost: 200 cr."),
  cyber("Data Plug Internal Link", "com:Sensors & Implants", 3000,
    "A connector jack built into a cybernetic or bionic prosthetic so a Cyber-Doc can jack in for an instant systems or data readout. Most Bio-Comp, recorder and cyber-computer systems have such an external jack so an outside computer/monitor can retrieve or share the data within.",
    "Location: any prosthetic. Cost: 3,000 cr each."),
  cyber("Depth Gauge (Cybernetic)", "com:Sensors & Implants", 4000,
    "Popular among SCUBA divers, deep-sea explorers and fishermen. Measures ocean depth and water pressure. The standard model hooks to an ear implant or radio chip, transmitting a ping per foot of depth and an audio (or HUD) depth statement every 10 feet (3 m); a warning sounds at dangerous depths.",
    "Location: internal. Cost: 4,000 cr standard; 600 cr inexpensive model that merely vibrates at dangerous depths."),
  cyber("Gyro-Compass (Cybernetic)", "com:Sensors & Implants", 600,
    "Implanted almost anywhere. Always locates North and the other directions, plus up and down. Ideal for pilots of aircraft and power armor and for underwater operations. Data as audio through an ear implant or to a receiver/eye/computer (latter requires Finger- or Headjack).",
    "Location: anywhere. Cost: 600 cr."),
  cyber("Internal Comp-Calculator (Cybernetic)", "com:Sensors & Implants", 1000,
    "Tiny computerized calculator usually connected to a Headjack, ear implant or artificial eye. Responds to spoken, radio or computer transmitted math equations; the answer is transmitted through the Headjack, ear or eye implant.",
    "Location: head. Cost: basic math 1,000 cr; advanced math (algebra, geometry, calculus) 5,000 cr."),
  cyber("Metal Detector", "com:Sensors & Implants", 4500,
    "Usually built into a prosthetic hand or forearm. Waving the arm over an area or a person's body detects metal fragments, coins, concealed weapons, and bionics.",
    "Location: Hand/Forearm. Range 2 ft (0.6 m); items covered in synthetic or real flesh only 10% chance of detection. Cost: 4,500 cr. Note: many S.D.C. cybernetics are high-impact plastic/ceramic (invisible to metal detection), as are Bio-Systems; bionics use composite M.D.C. materials including metal alloys."),
  cyber("Motion Detector (Cybernetic)", "com:Sensors & Implants", 15000,
    "Usually built into a sensor hand or prosthetic with hair-like sensor wires (or implanted in the arm, leg or head with wires hidden among human hair — wires must not be covered). Measures noticeable movement: wind direction/speed, rapid approach of large objects (vehicle, aircraft, power armor) within ~500 ft (153 m), movement of somebody within 40 ft (12 m) if the user is motionless, sudden air pressure changes (doors/windows), and speed estimation in open-air vehicles. Especially useful in the dark.",
    "Location: Hand/Arm/Leg/Head. Cost: 15,000 cr implant / half if built into a prosthetic."),
  cyber("Plug-in Hand-Held Monitor", "com:Sensors & Implants", 1000,
    "A simple hand-held view screen that plugs into any of the 'Borg's jacks for a complete readout of the bionic systems (what's working and what's not, Bio-Comp stats, etc.), or to read data collected by the cyborg's sensors — the person with the monitor sees everything (data stream) the cyborg sees.",
    "External accessory. Cost: 1,000 cr per unit."),
  cyber("Power Chip", "com:Sensors & Implants", 5000,
    "A tiny battery used to supplement implants with limited energy supplies, like tracer chips.",
    "Location: anywhere. Duration typically 72 hours. Cost: 5,000 cr."),
  cyber("Radar Sensor (Cybernetic)", "com:Sensors & Implants", 2000,
    "A warning is transmitted whenever the sensor detects it is being scanned by radar.",
    "Location: internal. Direction accuracy only 68% (roll percentile). Cost: 2,000 cr."),
  cyber("Radiation Sensor", "com:Sensors & Implants", 1200,
    "Detects and measures harmful radiation — nuclear, atomic, and microwave — and warns its owner. Data to an ear implant, cybernetic eye or wristwatch monitor; most sound an audio warning plus a visual display, and some tick like a Geiger counter, louder and faster as radiation increases.",
    "Location: internal. Cost: 1,200 cr."),
  cyber("Security Clearance Access Chip", "com:Sensors & Implants", 1500,
    "Encoded ID chips used by police, military and corporate security of high-tech cities and nations. Implanted under the skin (usually neck, behind the ear, nose, hand or forearm). Recognized by security devices to allow access to particular areas, offices, vehicles, computers and machines. Devices that don't recognize the chip lock the character out and may sound a silent or audio alarm.",
    "Location: under skin. Cost: basic chip 500 cr; top security 1,500 cr; military quality 2,500 cr. Top facilities add redundant DNA screens."),
  cyber("Sensor Hand (Standard)", "com:Sensors & Implants", 20000,
    "A special prosthetic hand filled with sensors, replacing a severed hand (mechanical or deluxe Bio-System with living tissue). Simulates the original limb, plus built-in: Heat sensor, Motion Detector, Radiation Detector, Radar Detection, Gyro-Compass, and Clock Calendar. Data transmits to a tiny ear receiver on the eardrum and/or wristband receiver (LCD, looks like a wristwatch) or a pocket-calculator-sized hand unit.",
    "Location: Hand. Cost: 20,000 cr mechanical / 33,000 cr Bio-System, plus receivers: ear receiver 1,000 cr (addable to other ear implants), wristband monitor 250-500 cr, pocket receiver-monitor 100 cr. Multiple receivers can link. Data can transmit to cybernetic eyes, NOT Bio-System eyes."),
  cyber("Simple I.D. Chip", "com:Sensors & Implants", 400,
    "A chip implant transmitting a signal recognized by sensors at key junctions like entrances and doors. If the door sensor does not recognize the signal, a silent or audio alarm sounds and security responds.",
    "Location: under skin. Cost: 300-500 cr."),
  cyber("Simple I.D. Computer Chip", "com:Sensors & Implants", 1500,
    "A tiny implant that transmits a signal to sensors or can be accessed via a computer connector plug. Once accessed, provides pertinent data about the individual: age, race, employment history, security clearance, and personal I.D. code.",
    "Location: under skin. Cost: 1,500 cr."),
  cyber("Body Attachments (Snaps, Hooks, Tabs, Loops, Velcro)", "com:Sensors & Implants", 100,
    "Cybernetic attachments amazingly popular among the City Rats of Japan, Russia and Germany, catching on in North America — ornamentation (like body piercing) and functional accessories. Used to secure wigs and hairpieces, and to hold (often conceal — scalp, underarms, inner legs) small items: knives, ice picks, blackjacks, micro-lasers, mini-tools, markers, lighters, flashlights, computer disks, spy cameras, small packets, mini-discs, etc. The best are woven or bonded to the flesh, resistant to tearing, and hold items up to one pound (0.45 kg) with little or no discomfort.",
    "Location: scalp, chest, back, arms, underarms, legs. Cost: 100 cr per attachment; removal same cost, minimal to no scarring."),
  cyber("Speedometer", "com:Sensors & Implants", 400,
    "A simple sensor that indicates how fast the character is moving — running speed or as a passenger in a moving vehicle. Simple and cheap.",
    "Location: internal. Cost: 400 cr; 1,200 cr advanced version with constant readout on a HUD in the corner of a bionic eye, wrist unit or plug-in monitor."),
  cyber("Universal Finger Camera", "com:Sensors & Implants", 1200,
    "A tiny still camera in the tip of one finger. Shoots 48 photos on microfilm; auto-adjusts for low or high light exposures.",
    "Location: Finger. Cost: 1,200 cr."),
  cyber("Universal Finger Jack", "com:Sensors & Implants", 10000,
    "A special connector jack built into one of the fingers, allowing the character to plug directly into most sophisticated computers, audio and sensory equipment, radios, video systems, microphones, and conventional items such as CD players. A tiny ear receiver linked to the Finger Jack receives audio transmissions.",
    "Location: Finger. Cost: 10,000 cr."),
  cyber("Universal Laser Finger Scalpel", "com:Sensors & Implants", 5000,
    "One of the fingers is really a laser scalpel used for surgery. Maximum damage is 1D4 S.D.C. points. It is not a Mega-Damage weapon.",
    "Location: Finger. Cost: 5,000 cr."),

  // ═══ COMMERCIAL AUDIO, EAR & HEAD IMPLANTS ═══════════════
  cyber("Amplified Hearing (Cybernetic)", "com:Audio & Ear", 20000,
    "Tiny sound amplifiers, microphones and receivers built into the ear canal. Hear almost inaudible sounds up to 360 ft (110 m): 1 decibel at 75 ft, a whisper (10 dB) clearly at 150 ft, normal conversation (30 dB) at 360 ft as if standing a meter away — the maximum eavesdropping range. Sounds of 70+ dB can be heard and pinpointed from 500-1,000 ft. Accurately estimate distance/location of sound sources; recognize specific sounds and voices at 35% +5% per level. Background noise, closed doors and walls decrease range and clarity.",
    "Location: Ear. Bonuses: +1 to parry, +2 to dodge, +3 on initiative. Cost: 20,000 cr."),
  cyber("Language Translator (Cybernetic)", "com:Audio & Ear", 16000,
    "Miniaturized language translator placed inside the body for easy communication with the multitude of nonhuman life forms on Rifts Earth. Starts with 10 languages; 8 more can be added. Accuracy 98.7% with one or two speakers/languages at a time; drops to 70% with a 6-second delay for 3-6 simultaneous speakers, 22% beyond that.",
    "Location: internal (ear). Cost: 16,000 cr full system (requires an ear implant if none exists); HALF cost if a Headjack or other audio ear implant pre-exists (integrated cyber-translator)."),
  cyber("Radio Chip (Advanced)", "com:Audio & Ear", 3000,
    "Usually implanted in the ear or at the base of the skull. A radio receiver for public radio and television bands with superior quality and depth of sound. Channels changed via a tiny hand-held remote or a jacked-in computer/monitor. Most install it for recreation.",
    "Location: Ear/Skull base. Cost: 3,000 cr. +3,000 cr to pick up wide band and broadband including most police and military bands; 10,000 cr for broadband and 1,000 frequencies. The latter two are ILLEGAL in the Coalition States and some other places."),
  cyber("Radio & Scrambler Implant", "com:Audio & Ear", 80000,
    "EXPERIMENTAL & ILLEGAL. An implant with organic circuitry developed by the military enabling mental-control interface with a specially modified short-wave radio (for most cyborgs, housed in a back compartment). Range 100 miles (160 km), 800 frequencies, automatically scrambles and decodes all transmissions; can send scrambled and coded messages.",
    "Location: head + radio unit. Cost: 80,000 cr implant + 20,000 cr radio. INTERFERES WITH PSIONICS: range and duration reduced by 75%. Penalty if caught: 10,000 cr fine, criminal record, removal at perpetrator's cost; repeat/criminal use: 2D4 years prison. Illegal in the CS."),
  cyber("Radio Ear (Basic)", "com:Audio & Ear", 1200,
    "A cybernetic ear or implant that receives all commercial radio stations. Channels changed by a tiny hand-held remote or a jacked-in portable computer. Receive/listen only — cannot transmit.",
    "Location: Ear. Cost: 1,200 cr."),
  cyber("Radio Bandit's Ear", "com:Audio & Ear", 26000,
    "ILLEGAL broadband version: receive 1,000 radio channels and frequencies including police, emergency and most common military bands, plus most commercial television (hear AND view TV signals given a monitor or bionic eyes). Can intercept and unscramble coded messages (01-59% success, -10% vs Coalition transmissions). Channels changed by hand-held remote or jacked-in computer; a bionic jaw can take a special unit to change channels by grinding the jaw.",
    "Location: Ear. Cost: 26,000-36,000 cr."),
  cyber("Radio Signal Booster", "com:Audio & Ear", 5000,
    "A small power supply implanted to boost the strength/signals of computer and communication implants; increases clarity of sound and increases range by 25%.",
    "Location: internal. Cost: 5,000-7,000 cr (higher price in most 'Burbs)."),
  cyber("Sound Filtration System", "com:Audio & Ear", 3500,
    "An ear accessory combinable with a Headjack, Amplified or Ultra-Ear, or most bionic/cybernetic ear implants. Automatically reacts to diminish potentially damaging sounds with filters and/or earplugs — muffles gunfire, explosions, heavy machinery and painful sound waves to protect against deafening or disorienting levels.",
    "Location: Ear (accessory). Cost: 3,500 cr; can only be added to an already existing cybernetic ear implant."),
  cyber("Sound Identifier", "com:Audio & Ear", 30000,
    "An ear implant programmable to recognize up to a dozen specific sounds or voices. Used to identify, track and pinpoint a specific vehicle, device or individual by its distinctive sound. An exact sample is required for programming — via any audio recording, or by listening and recording live with the implant.",
    "Location: Ear. Cost: 30,000 cr."),
  cyber("Surveillance Ear", "com:Audio & Ear", 600,
    "An ear accessory combinable with a Headjack, Amplified or Ultra-Ear, or most ear implants. Tunes to a specific hidden listening device (bug), and works like a stethoscope/parabolic dish — press the ear to a wall or door to hear a muffled but relatively clear conversation on the other side (2D6+80% heard clearly, tell how many speakers, etc.).",
    "Location: Ear (accessory). While listening intently: -2 on initiative, and anyone sneaking toward the listener is +10% to Prowl. Cost: 600 cr."),
  cyber("Telephone Jack (Connector)", "com:Audio & Ear", 800,
    "Jack into telephone lines to use them for free or to eavesdrop (must tap the specific line). Local telephone and regional internet services are available at high-tech cities and at least half of the 'Burbs.",
    "Location: Ear (add-on to existing ear implant). Eavesdropping tell: other parties hear a double click every 4D6 seconds or a slight buzz throughout — those in the know may suspect monitoring. Cost: 800 cr."),
  cyber("Tracer/Locator Chip", "com:Audio & Ear", 800,
    "Miniature tracking devices usually implanted on prisoners and suspects under the skin of the scalp, behind the ear or under the arm. Emits a signal tracked with a portable monitor/locator. About the size of a shirt button — easily discovered by simple bug detectors and easily removed.",
    "Location: under skin. Range ~3 mi (4.8 km) city / up to 10 mi (16 km) rural. Low-end: 7+ day life or draws from existing implants indefinitely; high-end draws energy from the living body indefinitely. Cost: 800 cr + 250 to install or remove. Sometimes illegal for average citizens. Illegal in the CS."),
  cyber("Tracer Bug and Tracker", "com:Audio & Ear", 800,
    "A conventional bug (button- to lighter-sized; pocket-slipped, lapel-pinned, or magnetically attached under a vehicle) is placed on the subject; the IMPLANT is the tracking device. Depending on other implants, links to ear implants (pinging/ticking faster and louder as you close in) or a HUD display in a cybernetic/bionic eye showing estimated distance.",
    "Location: internal (tracker). Cost: 800 cr for the tracker; bugs ~100-300 cr each."),
  cyber("Ultra-Ear", "com:Audio & Ear", 11000,
    "Like amplified hearing, but extends perception into the ultrasonic range — hearing like a bat. Perceive a TV capacitor's whine or a dog whistle up to 300 ft (91.5 m), a bird's wing flaps at 150 ft, low-frequency 'silent alarms', footsteps, fabric rustle, and a mouse's scurry at 150 ft (45.7 m). While engaged, normal-decibel sounds are unintelligible (conversations become a deep rumble), so the Ultra-Ear turns on and off as needed.",
    "Location: Ear. Cost: 11,000 cr as a separate unit; 5,500 cr added to an Amplified Hearing system."),
  cyber("Universal Headjack & Ear Implant", "com:Audio & Ear", 8400,
    "A connector jack built into the skull (base of head or behind the ear) linked to a tiny receiver on the eardrum. Plug into audio, sensory, robot and computer equipment: communications gear, radios, video systems, radar, detection devices, microphones, surveillance systems, plus CD players, TV, disc recorders, etc. Transmissions play so quietly inside the inner ear that only the character can hear them — even enhanced hearing cannot. The jack is easily concealed by hair or skin folds; the receiver is visible only by looking carefully into the ear with a light.",
    "Location: Skull/Ear. Cost: 8,400 cr basic.\nUpgrades: built-in radio receiver & transmitter (works like a walkie-talkie, transmits a whisper or voices within 6 ft, range 3 mi / 4.8 km) +16,000 cr. Long-range wide/broadband (requires additional surgery, jaw implant for channel switching, high-powered battery, micro-amplifier, skull antenna; range 50 mi / 80 km, or 100 mi / 160 km with a plug-in telescoping antenna) +48,000 cr. Combine with a camera eye or optic nerve implant to see video without an external monitor."),

  // ═══ COMMERCIAL COSMETIC CYBERNETICS ═════════════════════
  cyber("Antenna, Cosmetic", "com:Cosmetic", 800,
    "Simply for visual effect.", "Location: Head. Cost: 800 cr for a pair."),
  cyber("Antenna w/ Special Capabilities", "com:Cosmetic", 3000,
    "Can include most audio, camera or sensor systems at the usual price, plus the cost of a reinforced antenna.",
    "Location: Head. Cost: 3,000 cr for a pair, plus the systems installed."),
  cyber("Claws, Standard/Basic", "com:Cosmetic", 300,
    "Long hard fingernails made of high-tech polymers. From a beauty point of view, they never crack, chip or break unless put under a sledgehammer or vise.",
    "Location: Fingers. Damage: 1 S.D.C. raking an opponent. Cost: 200-400 cr."),
  cyber("Claws, Feline", "com:Cosmetic", 500,
    "Curved, sharp fingernails resembling the extended claws of a cat.",
    "Location: Fingers. Damage: 1D4 S.D.C. clawing/raking, but considered cosmetic. Cost: 400-600 cr."),
  {
    name: "Claws, Feline & Retractable",
    type: "weapon",
    img: "icons/commodities/claws/claw-steel-grey.webp",
    folder: loc["com:Cosmetic"].id,
    system: {
      equipped: false,
      description: "Requires a cybernetic prosthetic or bionic hand. The claws are a concealed weapon, extended only to inflict damage or intimidate others.",
      damage: "2d4",
      damageType: "MDC",
      range: "melee",
      rateOfFire: "1",
      payload: 0,
      weight: "",
      cost: 3000,
      bonusToStrike: 0,
      special: "M.D.C. claws are mini-Vibro-Blades: 2D4 M.D. per finger claw (+P.S. damage bonus, if any).\nS.D.C. variant: 1D4 S.D.C. per finger claw (+P.S. damage bonus, if any) — set damage to 1d4/SDC if taken.\nBoth types of finger blades/claws are ILLEGAL, but City Rats and others persist in getting them. Mega-Damage weapons always have the greatest fines and penalties.",
      notes: "Location: Fingers (cybernetic/bionic hand required). Cost: 1,200 cr per S.D.C. claw / 3,000 cr per M.D.C. claw; 15,000 cr to put a claw on each finger of one hand.",
    },
  },
  cyber("Cyber-Breasts", "com:Cosmetic", 9000,
    "These implants serve to keep the breasts firm without the need of outside support (i.e., a bra), and can also increase and decrease the size of the breasts by one cup size. Can also \"mold\" the breasts to flatten, to protect them from damage or to better fit a particular style of dress or blouse. Extremely popular among women of all ages.",
    "Location: Chest. Cost: 8,000-10,000 cr per pair. Lifelike prosthetic breasts with the same features: 12,000 cr; 20,000 for Bio-Systems."),
  cyber("Ears, Animal-like", "com:Cosmetic", 800,
    "Typically feline or canine ears mounted on top of the head like an animal or Dog Boy. The ears can usually move like a cat's or dog's, but have NO actual audio capabilities unless a radio or other listening/sensor implant is concealed within. The original ears are almost always kept too, often covered by hair.",
    "Location: Top of head. Augmented hearing (like the Ultra-Ear and Amplified Hearing) can NOT be used in the faux ears. Cost: 600-1,000 cr each; 2,000-3,000 for living Bio-System ears."),
  cyber("Ears, Delicate and Small", "com:Cosmetic", 850,
    "The original human ears are replaced with small artificial ones of any shape and configuration.",
    "Location: Ears. Cost: 700-1,000 cr each; 2,000-3,000 for living Bio-System ears (the price is comparatively high only because the customer is willing to pay for delicate ears). VERIFIED vs book."),
  cyber("Ears, Pointed", "com:Cosmetic", 550,
    "Pointed replacement ears; may be large or small.",
    "Location: Ears. Cost: 500-600 cr each (double for large); 1,500-2,000 for living Bio-System ears."),
  cyber("Ears, Round", "com:Cosmetic", 550,
    "Small or large round ears replace the original appendages.",
    "Location: Ears. Cost: 500-600 cr each; 1,500-2,000 for living Bio-System ears."),
  cyber("Cat Eye (Unique Cosmetic)", "com:Cosmetic", 15000,
    "Almond, feline shape, look and color; otherwise ordinary 20/20 vision.",
    "Location: Eye. Cost: 15,000 cr per lifelike cybernetic eye / 25,000 per Bio-System eye."),
  cyber("Round Eye (Unique Cosmetic)", "com:Cosmetic", 12000,
    "Large and round.", "Location: Eye. Cost: 12,000 cr per cybernetic simulated eye / 22,000 per Bio-System."),
  cyber("Strange Color Eye (Unique Cosmetic)", "com:Cosmetic", 10000,
    "300 colors and hues to choose from.",
    "Location: Eye. Cost: 10,000 cr per cybernetic simulated eye / 20,000 per Bio-System."),
  cyber("Mood or Color-Changing Eyes (Cybernetic)", "com:Cosmetic", 12000,
    "Lifelike cybernetic eye with 20/20 vision, no special powers other than changing 2-8 different colors to reflect the wearer's moods.",
    "Location: Eye. Cost: 12,000 cr per lifelike cyber-eye + 400 cr per color it can change to. (Bio-System version in Bio-Systems > Eyes.)"),
  cyber("Eyebrow Ridges", "com:Cosmetic", 600,
    "Cosmetic brow ridges.", "Location: Face. Cost: 500-700 cr each."),
  cyber("Eyebrow Spikes", "com:Cosmetic", 200,
    "Cosmetic brow spikes.", "Location: Face. Cost: 200 cr per spike."),
  cyber("Fin, Small", "com:Cosmetic", 700,
    "May be placed on the head, neck, spine or even the forearm.",
    "Location: Head/Neck/Spine/Forearm. Cost: 600-800 cr each."),
  cyber("Fin, Large", "com:Cosmetic", 1700,
    "Typically only one or two in any location. May be placed on the head, neck, spine or forearm.",
    "Location: Head/Neck/Spine/Forearm. Cost: 1,400-2,000 cr each."),
  cyber("Fin or Feather Crest", "com:Cosmetic", 1900,
    "A feather-like cluster of spines, plates or synthetic feathers that raises and lowers when the character is angry, happy, frightened, etc.",
    "Location: Head/Neck/Spine. Cost: 1,600-2,200 cr each."),
  cyber("Gruesome Cuts & Guts", "com:Cosmetic", 4000,
    "Cybernetics and fake coverings made to look like flesh peeled from the muscle (perhaps flapping in the wind), or a cybernetic/bionic arm made to look as if muscle and skin have been hacked or blasted away to show the bone or exoskeleton underneath. All fake — artistically designed to gross people out and impress friends. Popular among City Rats.",
    "Location: varies. Cost: 1,000-8,000 cr depending on how extensive and realistic."),
  cyber("Synthetic Hair Implants", "com:Cosmetic", 500,
    "Synthetic hair implants have made baldness obsolete except as a fashion statement. Different fibers and materials create looks and styles impossible or hard to maintain with normal hair — the perfect Mohawk, spiked hair, anime looks, huge manes, animal styles and patterns. Some implant stalks of hair on their arms or down the neck and spine.",
    "Location: anywhere. Cost: simple style 200-300 cr; modestly elaborate 500-800 cr; elaborate or exotic 1,500-5,000 cr."),
  cyber("Hair Mechanics (Cyber-Hair)", "com:Cosmetic", 1000,
    "Substitution of real hair with obviously fake, metallic or mechanical hair: thin or heavy chains, cascading metallic or plastic scales or hoops, straight or curled wire, hooks, metal balls, even colorful fiber-optic illuminated filaments. Hundreds of varieties, always with a high-tech, robotic or metallic look. Some Psi-Stalkers really go for it, usually in ponytail or Mohawk style.",
    "Location: Head+. Cost: simple 500-1,500 cr; fancy or exotic 3,000-6,000; rich & ornamental (precious metals and gems — more like jewelry than hair) 10,000-50,000+ cr."),

  // ═══ HEAD SHAPING IMPLANTS & BODY MODS ═══════════════════
  cyber("Balloon Head (Head Shaping)", "com:Head Shaping & Body Mods", 5500,
    "Head Shaping Implants are cybernetic bladders and ceramic skull plates designed to change the shape of the head. The Balloon Head is purposely made to look round like a ball — said to convey a cheerful, happy spirit. Ears and nose are typically made small and round also.",
    "Location: Head. Cost: 5,000-6,000 cr."),
  cyber("The Brainiac or Egg Head (Head Shaping)", "com:Head Shaping & Body Mods", 8000,
    "Makes the cranium appear oversized and bloated — an oval shape with the thick end on top, sometimes with a vague brain-like appearance to connote intelligence or just to look exotic.",
    "Location: Head. Cost: 7,000-9,000 cr."),
  cyber("Cone Head or Pin Head (Head Shaping)", "com:Head Shaping & Body Mods", 11000,
    "The skull is elongated and often comes to a point at the top; can also be a less conical, more fin-shaped cranium. In all cases, the shape is said to convey elegance and empathy.",
    "Location: Head. Cost: 10,000-12,000 cr."),
  cyber("Delicate Head (Head Shaping)", "com:Head Shaping & Body Mods", 20000,
    "The skull is rather thin, the nose small, facial features made thin and delicate — said to connote an aristocratic and gentle or refined spirit. One of the more expensive reshaping systems because it requires a lot of facial reconstruction or implantation.",
    "Location: Head. Cost: 20,000 cr."),
  cyber("Neanderthal (Head Shaping)", "com:Head Shaping & Body Mods", 6000,
    "A retro look making the cranium look small and heavy, the eyebrow ridges pronounced, the head and face more brutish. Said to connote strength; popular among Gutter Rats and thugs.",
    "Location: Head. Cost: 5,000-7,000 cr."),
  cyber("Horns, Small", "com:Head Shaping & Body Mods", 1000,
    "A pair of tiny to small Devil's or goat's horns. Usually for cosmetic effect rather than as a weapon.",
    "Location: Head. Damage Bonus: +1 S.D.C. to head butts. Cost: 1,000 cr."),
  cyber("Horns, Large", "com:Head Shaping & Body Mods", 5000,
    "A pair of large, bull or steer type horns.",
    "Location: Head. Damage Bonus: +2D4 S.D.C. to head butts (or +1 M.D. if a Full Conversion Cyborg). Cost: 5,000 cr."),
  cyber("Horns, Large Ram's Horn (Curled)", "com:Head Shaping & Body Mods", 8000,
    "A large set of thick, curled horns.",
    "Location: Head. Damage Bonus: +2D6 S.D.C. to head butts (or +2 M.D. if a Full Conversion Cyborg or has a full bionic head/skull, neck and reinforced shoulders). Cost: 8,000 cr."),
  cyber("Horn, Unicorn", "com:Head Shaping & Body Mods", 3000,
    "One large horn (any style), usually in the center of the forehead or top of the head.",
    "Location: Head. Damage Bonus: +1D6 S.D.C. to head butts. Cost: 3,000 cr."),
  cyber("Human Skin (Synthetic)", "com:Head Shaping & Body Mods", 1000,
    "A synthetic covering that looks and feels like human skin, only a bit more 'plastic' looking. Easily passes for real from a distance or quick glance — only noticeable as synthetic when examined closely. Usually cool and smooth to the touch.",
    "Location: varies. Cost: about 1,000 cr per limb; double for chest and torso."),
  cyber("Inhuman Skin (Cyber-Skin)", "com:Head Shaping & Body Mods", 750,
    "Typically scaled like a reptile or fish, or patches of skin in an exotic color or covered in small bumps or spines. Often worn in patches or simple designs — a skull cap of shimmering reptilian or metallic (chain mail or scale mail) skin in place of hair, an insignia, or a design pattern on the face, arms, legs, chest or back similar to the stripes or spots of an animal.",
    "Location: varies. Cost varies with size: Small 200 cr; Medium 500-1,000 cr; Large (full length of an arm or leg, much of the chest or back) 2,000-6,000 cr."),
  cyber("Iron Jaw", "com:Head Shaping & Body Mods", 12500,
    "The lower jaw and teeth are obviously mechanical, giving the cyborg a rather robotic, often disturbingly metal-skeleton look to his lower jaw and mouth. Usually done to evoke fear.",
    "Location: Jaw. Damage Bonuses: +1D4 S.D.C. to bite attacks (or +1 M.D. to bites if a Full Conversion Cyborg or has a full bionic head/skull). Cost: 10,000-15,000 cr. VERIFIED vs book."),
  cyber("Lips, Full and Puffy", "com:Head Shaping & Body Mods", 4000,
    "A stylistic choice popular among hookers and upper-class city wives.",
    "Location: Mouth. P.B. Bonus: +1 point. Cost: 3,000-5,000 cr."),
  cyber("Lips, Slit Mouth", "com:Head Shaping & Body Mods", 1600,
    "A stylistic choice popular among those who like the 'extraterrestrial' look.",
    "Location: Mouth. P.B. Penalty: -1 point. Cost: 1,200-2,000 cr."),
  cyber("Mandible Mouth/Jaw", "com:Head Shaping & Body Mods", 6000,
    "The human mouth is replaced with an insect-like mandible reminiscent of a beetle or the Xiticix Digger.",
    "Location: Mouth/Jaw. Damage Bonuses: +1D6 S.D.C. to bite attacks. Full Conversion Cyborgs can get a BIONIC version that inflicts 2D4 M.D. P.B. Penalty: -2 points. Cost: 5,000-7,000 cr (20,000-30,000 cr for the bionic version)."),
  cyber("Spikes or Studs, Small", "com:Head Shaping & Body Mods", 500,
    "Often a half dozen to a dozen metal spikes or studs, worn on the forehead or top of the head, but also above the eyebrows, along the cheek bone, chin and jaw, knuckles, shoulders and elbows. May be arranged in a specific pattern or placed to make an insignia, letter or design. Metal studs are basically smooth, rounded spikes — not sharp or pointed.",
    "Location: varies. Damage Bonus: +2 S.D.C. to head butts per six spikes, or +1 from studs. Cost: 500 cr per set of three spikes or studs."),
  cyber("Spikes, Chin or Cheek", "com:Head Shaping & Body Mods", 170,
    "Metallic and colored chrome spikes used as adornment to make oneself more glamorous, dangerous or exotic looking. Sometimes made to look like quills or needles.",
    "Location: Face. Cost: 170 cr per spike; 50% more for chrome."),
  cyber("Skull Plate", "com:Head Shaping & Body Mods", 2500,
    "Usually for both cosmetic appearance (may be chrome, silver, gold, bronze, copper, or some other metallic color) and physical protection.",
    "Location: Head. Provides the head with 10-25 M.D.C., as if wearing a light helmet. Cost: 2,000-3,000 cr."),
  cyber("Tongue of the Serpent", "com:Head Shaping & Body Mods", 4000,
    "A split tongue that looks like a snake's tongue. The character typically has a bit of a lisp and hissing sound to his speech pattern.",
    "Location: Mouth. Penalties: -15% to all speech, acting and language skills (a snake's tongue is simply not as articulated for speaking). Bonus: +1 to Horror Factor (if applicable). Cost: 4,000 cr."),
  cyber("Tongue, Spiked", "com:Head Shaping & Body Mods", 1100,
    "1-4 small spikes stick out of the tongue. The character tends to slur his words or mumble.",
    "Location: Mouth. Penalties: -10% to all speech, acting and language skills. Bonus: +1 to Horror Factor (if applicable). Cost: 1,100 cr."),
  cyber("Transparent Skin", "com:Head Shaping & Body Mods", 2500,
    "A macabre cosmetic modification. One variation uses a CLEAR synthetic skin so that the muscles, veins and perhaps bone show through. Another uses a clear plastic covering over cybernetics and bionics so observers can see the inner workings of the cyborg — making the character something of a 'clockwork' man.",
    "Location: varies. Cost varies with extent: 1,000-1,500 cr for something hand-sized; 2,000-3,000 for a forearm; 4,000-6,000 for the belly or an entire arm or leg; and so on."),
  cyber("Vampire Teeth", "com:Head Shaping & Body Mods", 450,
    "Exactly what it sounds like — the human canines are replaced by a pair of large, fang-like teeth.",
    "Location: Mouth. Damage Bonus: bite attacks do an extra 1D4 damage. Penalty: slurs speech a bit, -10% to all speaking and performance related skills and -1 to P.B. Cost: 300-600 cr."),
  cyber("Vestigial Tail", "com:Head Shaping & Body Mods", 1200,
    "A popular trend, especially among female City Rats and teenagers: a cuddly animal tail. Feline tails and fluffy fox-like tails are the most desirable. The cybernetic tail can move in a swishing, up and down, side to side way like a cat or dog.",
    "Location: Tail. NOT prehensile and cannot be used as a weapon. Cost: 700-1,800 cr depending on size and quality."),
  cyber("Vestigial Wings", "com:Head Shaping & Body Mods", 4500,
    "Artificial wings that can move, spread open, tuck back and react to the wearer's emotions and wishes — but can NOT actually fly or glide. Purely cosmetic; in most cases (80%) the wings are small and undersized to the wearer's proportion. M.D.C. vestigial wings are typically worn by City Rats, partial cyborgs and light cyborgs for dramatic or exotic effect.",
    "Location: Back. S.D.C. wings: 1D4x10+30 S.D.C., usually soft and sensual — 3,000-6,000 cr. M.D.C. wings: 2D6+20 M.D.C., typically mechanical, expensive and often illegal — 30,000-60,000 cr. Partial reconstruction or full conversion cyborgs with wings hooked directly to their bionic spine and motor system: 40-70 M.D.C. Both varieties have limited movement and cannot be used as a weapon or means of flight."),
  cyber("Webbed Hands and/or Feet", "com:Head Shaping & Body Mods", 1000,
    "Typically appealing to professional swimmers, divers and athletes, as well as those who think it makes them look exotic.",
    "Location: Hands/Feet. Bonus: +5% to swimming speed. Cost: 800-1,200 cr per pair of hands or feet."),
  cyber("Wheel or Tread Legs", "com:Head Shaping & Body Mods", 55000,
    "The wheeled or tread system of locomotion replaces the legs completely. Rare and usually illegal machine augmentation, typically acquired only by technophiles who prefer to look more like a machine than a human or humanoid.",
    "Location: Legs (full replacement). Maximum Speed: 60 mph (96 km), with 30-40 mph (48-64 km) most common. Cost: 40,000-75,000 cr for gasoline, electric or solar powered treads/wheels; 1.2-2.5 MILLION for a nuclear power supply. Illegal in the Coalition States and Free Quebec; frowned upon by the CS in the 'Burbs — those with machine legs are frequently roughed up, interrogated, abused and mistreated without just cause."),

];

// ── Create items; move existing ones into their folders ───
const index = await pack.getIndex();
const byName = new Map(index.map((e) => [e.name, e]));

let created = 0;
let moved = 0;
for (const itemData of items) {
  const entry = byName.get(itemData.name);
  if (entry) {
    if ((entry.folder ?? null) !== itemData.folder) {
      const doc = await pack.getDocument(entry._id);
      await doc.update({ folder: itemData.folder });
      moved++;
    }
    continue;
  }
  await Item.create(itemData, { pack: `world.${PACK_NAME}` });
  created++;
}

ui.notifications.info(`${PACK_LABEL}: ${created} cybernetic item(s) added, ${moved} moved into folders, ${items.length - created - moved} already in place.`);
